apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: "b.parthchauhan@gmail.com"
  email-password: "your-gmail-app-password"  # Replace with your Gmail App Password
