apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/component: jobs
spec:
  project: chat-app-project
  source:
    repoURL: https://github.com/pb-tech009/aws-chat-app
    targetRevision: main
    path: helm/chat-jobs
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  revisionHistoryLimit: 5